version: '3'

services:
  apache:
    build: 
      context: ./apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mariadb-data:/bitnami