FROM ubuntu:24.04

ENTRYPOINT echo "Hello World!"
#ENTRYPOINT ["/bin/bash", "-c", "echo Hello World!"]
#ENTRYPOINT ["echo", "Hello World!"]

#CMD echo "Hello World!"
#CMD ["echo", "Hello World!"]
#CMD ["/bin/bash", "-c", "echo Hello World!"]